// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxqUQXDsdfEcYXzqX6Ns5TSJrpQXB-Nkw',
    appId: '1:682142070711:web:9f70b154e076359e10da32',
    messagingSenderId: '682142070711',
    projectId: 'bazar-app-2383b',
    authDomain: 'bazar-app-2383b.firebaseapp.com',
    storageBucket: 'bazar-app-2383b.firebasestorage.app',
    measurementId: 'G-D2DS1QQJ33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkrao4U4vdq6-RoYlz6TfSIW_z83_2v5M',
    appId: '1:682142070711:android:ad604ea324d4e9b610da32',
    messagingSenderId: '682142070711',
    projectId: 'bazar-app-2383b',
    storageBucket: 'bazar-app-2383b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8eZOzbPm0IVVKvf9EaatTR4GhAcemsk',
    appId: '1:682142070711:ios:3aed0ef6b2e5fd6210da32',
    messagingSenderId: '682142070711',
    projectId: 'bazar-app-2383b',
    storageBucket: 'bazar-app-2383b.firebasestorage.app',
    androidClientId: '682142070711-3hie2tp5uc4m67aia1ht3vso0np3270a.apps.googleusercontent.com',
    iosClientId: '682142070711-i56t5knji6ngimcda3gj53aqgo1l6i1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8eZOzbPm0IVVKvf9EaatTR4GhAcemsk',
    appId: '1:682142070711:ios:3aed0ef6b2e5fd6210da32',
    messagingSenderId: '682142070711',
    projectId: 'bazar-app-2383b',
    storageBucket: 'bazar-app-2383b.firebasestorage.app',
    androidClientId: '682142070711-3hie2tp5uc4m67aia1ht3vso0np3270a.apps.googleusercontent.com',
    iosClientId: '682142070711-i56t5knji6ngimcda3gj53aqgo1l6i1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxqUQXDsdfEcYXzqX6Ns5TSJrpQXB-Nkw',
    appId: '1:682142070711:web:beb56b549ef0198310da32',
    messagingSenderId: '682142070711',
    projectId: 'bazar-app-2383b',
    authDomain: 'bazar-app-2383b.firebaseapp.com',
    storageBucket: 'bazar-app-2383b.firebasestorage.app',
    measurementId: 'G-6HSD8DL88B',
  );
}
